name: Spleeter Portable

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      mytag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input Tag'
        # Default value if no value is explicitly provided
        default: '0.0.0.0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-13, macos-latest, ubuntu-latest, windows-latest]
        os: [macos-13, ubuntu-latest, windows-latest]
        include:
          - os: macos-13
            os_name: darwin
            os_arch: universal2
          # - os: macos-latest
          #   os_name: darwin
          #   os_arch: universal2
          - os: ubuntu-latest
            os_name: linux
            os_arch: x86_64
          - os: windows-latest
            os_name: windows
            os_arch: x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Portable Python
        run: |
          curl -L -o spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip https://github.com/bjia56/portable-python/releases/download/cpython-v3.10.15-build.0/python-headless-3.10.15-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip

      - name: Extract Portable Python
        run: |
          if [[ ${{ matrix.os_name }} == 'windows' ]]; then
            powershell -command "Expand-Archive spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip -DestinationPath spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}"
          else
            unzip spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip -d spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}
          fi
        shell: bash

      - name: Set up environment path
        run: |
          if [[ ${{ matrix.os_name }} == 'windows' ]]; then
              echo "Adding to PATH"
              echo "spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}\\python-headless-3.10.15-${{ matrix.os_name }}-${{ matrix.os_arch }}\\bin" >> $GITHUB_PATH
              echo "spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}\\python-headless-3.10.15-${{ matrix.os_name }}-${{ matrix.os_arch }}\\Scripts" >> $GITHUB_PATH
          else
              echo "Adding to PATH"
              echo "spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}/python-headless-3.10.15-${{ matrix.os_name }}-${{ matrix.os_arch }}/bin" >> $GITHUB_PATH
              echo "spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}/python-headless-3.10.15-${{ matrix.os_name }}-${{ matrix.os_arch }}/Scripts" >> $GITHUB_PATH
          fi
        shell: bash

      - name: Enable Windows Long Path Support
        if: runner.os == 'Windows'
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        shell: powershell

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install numpy
        run: python -m pip install numpy==1.26.3

      - name: Install spleeter
        run: python -m pip install spleeter

      - name: Zip directory
        run: |
          if [ "${{ matrix.os_name }}" = "windows" ]; then
              powershell -command "Compress-Archive -Path spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }} -DestinationPath spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip"          
          else
              zip -r spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}
          fi
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip
          asset_name: spleeter-portable-${{ matrix.os_name }}-${{ matrix.os_arch }}.zip
          asset_content_type: application/zip
