name: Spleeter Portable

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      mytag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Input Tag'
        # Default value if no value is explicitly provided
        default: '0.0.0.0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Portable Python
        run: |
          case ${{ matrix.os }} in
            macos*)
              os_name=macos
              ;;
            ubuntu*)
              os_name=linux
              ;;
            windows*)
              os_name=windows
              ;;
          esac
          curl -L -o spleeter-portable-${os_name}-${{ runner.arch }}.zip https://github.com/bjia56/portable-python/releases/download/YOUR_RELEASE_VERSION/portable-python-${os_name}-${{ runner.arch }}.zip

      - name: Extract Portable Python
        run: |
          case ${{ matrix.os }} in
            macos*)
              os_name=macos
              unzip spleeter-portable-${os_name}-${{ runner.arch }}.zip -d spleeter-portable-${os_name}-${{ runner.arch }}
              ;;
            ubuntu*)
              os_name=linux
              unzip spleeter-portable-${os_name}-${{ runner.arch }}.zip -d spleeter-portable-${os_name}-${{ runner.arch }}
              ;;
            windows*)
              os_name=windows
              powershell -command "Expand-Archive spleeter-portable-${os_name}-${{ runner.arch }}.zip -DestinationPath spleeter-portable-${os_name}-${{ runner.arch }}"
              ;;
          esac

      - name: Set up environment path
        run: |
          case ${{ matrix.os }} in
            macos* | ubuntu*)
              echo "Adding to PATH"
              echo "spleeter-portable-${os_name}-${{ runner.arch }}/bin" >> $GITHUB_ENV
              echo "spleeter-portable-${os_name}-${{ runner.arch }}/Scripts" >> $GITHUB_ENV
              ;;
            windows*)
              echo "Adding to PATH"
              echo "spleeter-portable-${os_name}-${{ runner.arch }}\\bin" >> $GITHUB_ENV
              echo "spleeter-portable-${os_name}-${{ runner.arch }}\\Scripts" >> $GITHUB_ENV
              ;;
          esac

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install numpy
        run: python -m pip install numpy==1.26.3

      - name: Install spleeter
        run: python -m pip install spleeter

      - name: Zip directory
        run: |
          case ${{ matrix.os }} in
            macos* | ubuntu*)
              zip -r spleeter-portable-${os_name}-${{ runner.arch }}.zip spleeter-portable-${os_name}-${{ runner.arch }}
              ;;
            windows*)
              powershell -command "Compress-Archive -Path spleeter-portable-${os_name}-${{ runner.arch }} -DestinationPath spleeter-portable-${os_name}-${{ runner.arch }}.zip"
              ;;
          esac

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: spleeter-portable-${os_name}-${{ runner.arch }}.zip
          asset_name: spleeter-portable-${os_name}-${{ runner.arch }}.zip
          asset_content_type: application/zip
